CREATE TABLE IF NOT EXISTS Customer(
  id IDENTITY PRIMARY KEY,
  customerName VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  groupName VARCHAR(255) NOT NULL,
  companyName VARCHAR(255) NOT NULL,
  innerName VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CustomerOrder(
  id IDENTITY PRIMARY KEY,
  customerName VARCHAR(255) NOT NULL,
  groupName VARCHAR(255) NOT NULL,
  companyName VARCHAR(255) NOT NULL,
  customerInnerName VARCHAR(255) NOT NULL,
  sequence VARCHAR(255) NOT NULL,
  scale DECIMAL NOT NULL,
  purification VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  orderDate TIMESTAMP DEFAULT current_timestamp NOT NULL,
  status VARCHAR(255) NOT NULL,
  price INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS LaborUser(
  id IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Purification(
  id IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Type(
  id IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL
);